### ISSUE TITLE
Ability To Use Without NPM

### ISSUE THREAD

**Issue by s0kil** [ryanve/speculative#1]
Thanks For this Lib!

I was wondering if there is a way to use it without a bundler.
Currently, I get an error when trying link script in an HTML page.
`Cannot set property 'speculative' of undefined`

**Comment by ryanve** [comment]
Sure! How are you loading your scripts? If you load the [speculative.js](https://github.com/ryanve/speculative/blob/0.1.2/speculative.js) directly via its own `<script>` tag then `speculative` gets assigned to the global `window` object because in that context `this === window`

```html
<script src="https://unpkg.com/speculative@0.1.2/speculative.js"></script>
```

The `undefined` error you got makes me guess that `this === undefined` as it would be in strict mode. FYI the the [UMD pattern used is like this](https://gist.github.com/ryanve/3d83e1f001a4a99e25bd022be3ff1250#file-umd-md) where `root` is the outer `this`
